version: 0.2
phases:
  install:
    commands:
      - echo Installing kubectl
      - curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
  pre_build:
    commands:
      - echo Setting up kubeconfig
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_DEFAULT_REGION
  build:
    commands:
      - echo Applying manifests
      - kubectl apply -R -f deploy/
